### ISSUE TITLE
Chapter 2: System Design

### ISSUE THREAD

**Issue by viejoy** [NoFoodsNoEntry/rice-blast-detection#9]
Includes:

- [x] Architectural Design
- [ ] Database Design
- [ ] Procedural and Object-Oriented Design

Notes:
- Refer to the picture taken form the library.

**Comment by viejoy** [comment]
[system design.txt](https://github.com/NoFoodsNoEntry/rice-blast-detection/files/1664937/system.design.txt)

Notes:
- Graphs, tables, and figures needed.

**Comment by hazelsweet** [comment]
[Architectural design.docx](https://github.com/NoFoodsNoEntry/rice-blast-detection/files/1666353/Architectural.design.docx)

Notes:
- Archi design picture

**Comment by viejoy** [comment]
[Architectural design.docx](https://github.com/NoFoodsNoEntry/rice-blast-detection/files/1750589/Architectural.design.docx)
[Procedural Design.docx](https://github.com/NoFoodsNoEntry/rice-blast-detection/files/1750590/Procedural.Design.docx)
